### ISSUE TITLE
Problemas com lançamentos de erros

### ISSUE THREAD

**Issue by JenniferERSS** [OpenAC-Net/OpenAC.Net.EscPos#4]
Bom dia.
Preciso saber como capturar os erros que acontecem quando algo sai do controle. Estou utilizando a impressora Bematech MP-4200 TH e se eu trocar a impressora de porta e tentar imprimir, não imprime, mas também não lança nenhum tipo de erro, como por exemplo, impressora não encontrada, ou porta não reconhecida.
Como faço para capturar esses erros?

**Comment by rftd** [comment]
neste caso isso não ocorre pois a porta virtual continua a existir no não responde, o correto era ter um timeout, mas em meus testes a classe de comunicação serial não lança timeout e eu ainda não consegui corrigir este tipo de erro, então eu faço um time out simulado usando task ou thread.

**Comment by JenniferERSS** [comment]
Você poderia me dar um exemplo de solução temporária, que você exemplificou, em quanto não resolve de forma definitiva?.
Para eu poder ter mais confiança na segurança de usar o nugget?
