### ISSUE TITLE
Alinear impresión

### ISSUE THREAD

**Issue by yvcabrera** [OpenAC-Net/OpenAC.Net.EscPos#6]
Hola  @rftd @adrbarros   buenas tardes..

He estado probando el project, haciendo algunas impresiones en una impresora termica "RPT006"

He intentado probar la alineación de textos:

Ejemplo :

posprinter.ImprimirLinha();
                    posprinter.ImprimirTexto("**MENDOZA VIAJES [IZD]**", CmdFonte.Normal, CmdTamanhoFonte.Normal, CmdAlinhamento.Esquerda, CmdEstiloFonte.Negrito);
                    posprinter.ImprimirTexto("**MENDOZA VIAJES [CEN]**", CmdFonte.Normal, CmdTamanhoFonte.Normal, CmdAlinhamento.Centro, CmdEstiloFonte.Negrito);
                    posprinter.ImprimirTexto("**MENDOZA VIAJES [DER]**", CmdFonte.Normal, CmdTamanhoFonte.Normal, CmdAlinhamento.Direita, CmdEstiloFonte.Negrito);
                    posprinter.ImprimirLinha();

![image](https://github.com/OpenAC-Net/OpenAC.Net.EscPos/assets/16673786/969135b1-57f3-463b-8d67-dfe508b96716)

Muestro en la captura, todos los textos salen alineados a la izquierda. Hay alguna otra forma de poder configurar y salgan de manera correcta.

Saludos..

**Comment by adrbarros** [comment]
Saludos, @yvcabrera 

Leyendo el Manual, no pude encontrar que Protocolo usa este modelo de Impresora, seguiré investigando para saber como hacer las implementaciones necesarias para la correcta impresión de los alineamientos

**Comment by yvcabrera** [comment]
Hola @adrbarros  Buenas noches. Gracias por la respuesta.

El link de la página del fabricante es : https://3nstar.com/producto/direct-thermal-receipt-printer-80mm-3-rpt006/?lang=es#

En la documentación indica [https://3nstar.com/wp-content/uploads/2020/07/RPT006-User-Manual.pdf]:

Print command: Compatible with ESC/POS commands

![image](https://github.com/OpenAC-Net/OpenAC.Net.EscPos/assets/16673786/82cdeb09-44ac-4aee-a77c-72b27b25d66e)


Saludos..

**Comment by rftd** [comment]
Ja tentou usar o PosStar, pois apesar de dizer que usa escpos muitas dessas impressoras chineses usam variações próprias do escpos
