### ISSUE TITLE
ModoPagina

### ISSUE THREAD

**Issue by yvcabrera** [OpenAC-Net/OpenAC.Net.EscPos#7]
Hola @rftd @adrbarros buenos días..

Tienen algún ejemplo de como utilizar la impresión en "MODO PAGINA".

Sería posible imprimir un [documento pdf o una imagen], con orientación vertical.

![image](https://github.com/OpenAC-Net/OpenAC.Net.EscPos/assets/16673786/c3f61564-0834-45bb-a8d7-6d9f6af25310)

Muchas gracias..

**Comment by rftd** [comment]
Este componente não gera documentos pdf ou imagem

**Comment by yvcabrera** [comment]
La idea no es generar el documento, la idea es imprimir una imagen  o un
documento pdf utilizando " MODO PAGINA "

**Comment by yvcabrera** [comment]
> Este componente não gera documentos pdf ou imagem. Mas o modo pagina sim serve para fazer impressão na vertical, mas a impressora precisa ser compatível com modo pagina.

@rftd  Algún ejemplo que imprima utilizando el modo pagina ?

**Comment by rftd** [comment]
O modo pagina não é exatamente para isso, se quer imprimir imagem basta usar o comando imprimir imagem.
Agora para imprimir PDF não é possível.
O modo pagina é para dividir em pequenas partes a area de impressão.
Ex: Imprimir o QrCode da NFe e o texto do lado.

**Comment by rftd** [comment]
> > Este componente não gera documentos pdf ou imagem. Mas o modo pagina sim serve para fazer impressão na vertical, mas a impressora precisa ser compatível com modo pagina.
> 
> @rftd Algún ejemplo que imprima utilizando el modo pagina ?

No demo quem tem no repositório tem um exemplo do uso do modo pagina.
