### ISSUE TITLE
Integração impressão via conexão Bluetooth Android. 

### ISSUE THREAD

**Issue by khaddmussistemas** [OpenAC-Net/OpenAC.Net.EscPos#8]
Olá pessoal, 

Estou com uns projetos Xamain Forms e Net Maui,  gostaria de ver a possibilidade de impressão da NFCe eu passando o XMl, naquelas impressora Bluetooth mini.
È possivel? vcs conhece alguma lib que faz isso?
Grato de mais.

**Comment by rftd** [comment]
Infelizmente não temos nada disponivel para Bluetooth na nossa lib.
